name: Python (Conda)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-activate-base: false
          channels: conda-forge,defaults
          use-mamba: false

      - name: Install dependencies (using conda)
        shell: bash -l {0}
        run: |
          conda create -n test-env --yes python=3.10 pip
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate test-env
          pip install -r backend/requirements.txt

      - name: Run checks
        shell: bash -l {0}
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate test-env
          python -m compileall backend
